### ISSUE TITLE
Custom Sprite appears on the floor & XML issues.

### ISSUE THREAD

**Issue by Goomboi** [BurntBread007/Funkin-XML-Editor#3]
After making the sprite with the XML sheet as well, I end up getting the sprite to work and getting the sprite to fall into the floor. Also, a few issues, which I think may be from the XML sheet, such as the scared animation ending up into the idle animation, somehow.

**Comment by Goomboi** [comment]
Another thing, bits of the scared and idle animation also get bugged into the death start animation from the XML sheet

**Comment by Goomboi** [comment]
Update, i messed up the dimensions 🤦‍♂️

**Comment by BurntBread007** [comment]
Sorry for replying to this issue so late, I wasn't aware of this until now. I know the bug you are talking about. The XML skipped the first frame at (0,0) on the spritesheet, shifting all of the frames in the XML list by one, causing the issue you described. 
I believe I have fixed this XML bug in my v0.4 release. If it happens in that release or in newer releases, please let me know, I wouldn't mind going back to fix it again.

**Comment by Burger-Gaming** [comment]
Great work! Thanks for fixing that. The only issue left is the fact that the sprites are on the floor and that's about it with XML issues. If I'm not mistaken the XML files in the vanilla game have offsets so that they can be put on the stage properly.

**Comment by BurntBread007** [comment]
Ah, thanks for the heads up. I didn't realize that there were offsets in the XML, so I just used the spacing size from the user instead of real offsets. I'll work on adding custom (and maybe some kind of automatic?) offset editing to the XML for my next update.

**Comment by Burger-Gaming** [comment]
I guess I can close this issue now. Thanks for clearing the majority of the XML issues!
